### PR TITLE
Testing SPM12 export of NIDM 1.0.0

### PR DESCRIPTION
**Pull request by gllmflndn**

### CODE REVIEW

**Comment by cmaumet** [comment]
Hi @gllmflndn, just to let you know that the list of `NIDM_***` and `SPM_***` constants defined in [Constants.py](https://github.com/incf-nidash/nidm/blob/master/scripts/Constants.py#L29-L204) might be useful for you as a starting point to move to alphanumeric identifiers...

**Comment by gllmflndn** [comment]
Thanks @cmaumet, will have a look!

**Comment by cmaumet** [comment]
@gllmflndn: I have just relaunched the tests following the merge of incf-nidash/nidm#325. The error messages should now (hopefully) be more explicit...

**Comment by cmaumet** [comment]
The tests now pass so I think this is good to merge.

**Pull request merged**
